Created commentary and support systems using forms
florantis/hillel pull request #8
Opened 2023-06-29 21:56 UTC by florantis

I came up with two different uses of forms for my Monopoly site: 

- Comments for a page (currently we comment as user TheMonopolier)
- User support tickets

For comments I used forms.Form, but for support tickets - forms.ModelForm (so that I try out both of them).
Tried to adapt the requirements of the HW6 to my project, I think it turned out well.

Also created two views using generic view classes

2023-06-29 21:57 UTC, florantis commented on monopoly/user_profile/forms.py
> +        if "communism" in data.lower():
had to come up with original joke for some kind of restriction

2023-06-29 22:00 UTC, florantis commented on monopoly/user_profile/forms.py
> +        return self.cleaned_data.get("assignee")
I could avoid repeating the return statement, but that way there would be multiple same entries in the error list (also, that way it is potentially slightly faster)

2023-06-30 14:33 UTC, florantis commented on monopoly/user_profile/forms.py
> +        return self.cleaned_data.get("assignee")
I could avoid repeating the return statement, but that way there would be multiple same entries in the error list (also, that way it is potentially slightly faster)

2023-07-06 17:37 UTC, idegtiarov requested changes

2023-07-06 17:37 UTC, idegtiarov commented on monopoly/user_profile/forms.py
> +        if (cleaned_data["assignee"] and not cleaned_data["email"] or \
It could be a case that one of the fields is not exists so you will get KeyError, it would be better to use get method instead

not an error but common practice is not to use '\' symbol for new line jumping, it is better to use parenthesis instead.

2023-07-06 17:37 UTC, idegtiarov commented on monopoly/user_profile/forms.py
> +        for num in (0, 1, 2, 3, 4, 5, 6, 7, 8, 9):
It would be better to use mathematic comparison instead of checking item equality in a list
if 0<= num < 10:

2023-07-06 20:22 UTC, merged